# Source: iap/templates/configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iap-config-map
  namespace: {{ .Values.namespace }}
data:
  custom-properties.json: |
    {
      "id": "{{ .Values.propertiesJson.profileId }}",
      "mongoProps": {
        "credentials": {
          "dbAuth": {{ .Values.propertiesJson.dbAuth }},
          "passwd": "{{ .Values.propertiesJson.dbPassword }}",
          "user": "{{ .Values.propertiesJson.dbUsername }}"
        },
        "db": "{{ .Values.propertiesJson.dbName }}",
        "ssl": {
          "acceptInvalidCerts": {{ .Values.propertiesJson.acceptInvalidCerts }},
          "checkServerIdentity": {{ .Values.propertiesJson.checkServerIdentity }},
          "enabled": {{ .Values.propertiesJson.sslEnabled }},
          "sslCA": "{{ .Values.propertiesJson.sslCA }}",
          "sslValidate": {{ .Values.propertiesJson.sslValidate }}
        },
        "url": "{{ .Values.propertiesJson.dbUrl }}"
      },
      "pathProps": {
        "description": "File Path Variables",
        "encrypted": true,
        "sdk_dir": "/opt/pronghorn-applications"
      },
      "processJobsOnStart": {{ .Values.propertiesJson.processJobsOnStart }},
      "processTasksOnStart": {{ .Values.propertiesJson.processTasksOnStart }},
      "serverId": "{{ uuidv4 }}",
      "serverName": "",
      "vaultProps": null
    }